export const searchMovie = {
  LIKE_MOVIE: 'LIKE_MOVIE',
  CLEAR_ALLSTATE: 'CLEAR_ALLSTATE',
  MOVIE_FETCH_REQUESTED: 'MOVIE_FETCH_REQUESTED',
  MOVIE_FETCH_SUCCEEDED: 'MOVIE_FETCH_SUCCEEDED',
  MOVIE_FETCH_FAILED: 'MOVIE_FETCH_FAILED',
  REC_MOVIE_FETCH_REQUESTED: 'REC_MOVIE_FETCH_REQUESTED',
  REC_MOVIE_FETCH_SUCCEEDED: 'REC_MOVIE_FETCH_SUCCEEDED',
  REC_MOVIE_FETCH_FAILED: 'REC_MOVIE_FETCH_FAILED',
};
