exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('movies')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('movies').insert([
        { id: 1, name: 'Joker', image: '/images/1.png' },
        { id: 2, name: 'Iron Man', image: '/images/2.png' },
        { id: 3, name: 'The Incredible Hulk', image: '/images/3.png' },
        { id: 4, name: 'Iron Man 2', image: '/images/4.png' },
        { id: 5, name: 'Thor', image: '/images/5.png' },
        {
          id: 6,
          name: 'Captain America: The First Avenger',
          image: '/images/6.png',
        },
        { id: 7, name: 'Marvels The Avengers', image: '/images/7.png' },
        { id: 8, name: ' The Godfather: Part II', image: '/images/8.png' },
        { id: 9, name: 'The Lives of Others', image: '/images/9.png' },
        { id: 10, name: ' Avengers: Infinity War', image: '/images/10.png' },
        { id: 11, name: 'The Dark Knight Rises', image: '/images/11.png' },
        { id: 12, name: 'Your Name', image: '/images/12.png' },
        { id: 13, name: 'Coco', image: '/images/13.png' },
        { id: 14, name: '3 Idiots', image: '/images/14.png' },
        { id: 15, name: 'Like Stars on Earth', image: '/images/15.png' },
        { id: 16, name: 'Toy Story', image: '/images/16.png' },
        { id: 17, name: 'The Kid', image: '/images/17.png' },
        { id: 18, name: 'The Chaos Class', image: '/images/18.png' },
        { id: 19, name: 'Life Is Beautiful', image: '/images/19.png' },
        { id: 20, name: 'The Intouchables', image: '/images/20.png' },
        { id: 21, name: 'Back to the Future', image: '/images/21.png' },
        { id: 22, name: 'Modern Times', image: '/images/22.png' },
        { id: 23, name: 'Snatch', image: '/images/23.png' },
        {
          id: 24,
          name: 'Star Wars: Episode V - The Empire Strikes Back',
          image: '/images/24.png',
        },
        { id: 25, name: 'The Green Mile', image: '/images/25.png' },
        { id: 26, name: '12 Years a Slave', image: '/images/26.png' },
        { id: 27, name: 'Airlift', image: '/images/27.png' },
        { id: 28, name: 'Let the Right One In', image: '/images/28.png' },
        { id: 29, name: 'Night of the Living Dead', image: '/images/29.png' },
        { id: 30, name: 'I Saw the Devil', image: '/images/30.png' },
        { id: 31, name: 'Spirited Away', image: '/images/31.png' },
        { id: 32, name: 'The Prestige', image: '/images/32.png' },
        { id: 33, name: 'Bone Tomahawk', image: '/images/33.png' },
        { id: 34, name: 'The Lion King', image: '/images/34.png' },
        { id: 35, name: 'The Irishman', image: '/images/35.png' },
        { id: 36, name: 'Knives Out', image: '/images/36.png' },
        { id: 37, name: 'Marriage Story', image: '/images/37.png' },
        { id: 38, name: 'Little Women', image: '/images/38.png' },
        { id: 39, name: 'Green Book', image: '/images/39.png' },
        { id: 40, name: 'Logan', image: '/images/40.png' },
        { id: 41, name: 'Hacksaw Ridge', image: '/images/41.png' },
        { id: 42, name: 'Room', image: '/images/42.png' },
        { id: 43, name: 'A Quiet Place', image: '/images/43.png' },
        { id: 44, name: 'Parasite', image: '/images/44.png' },
        { id: 45, name: 'Doctor Sleep', image: '/images/45.png' },
        { id: 46, name: 'Rambo: Last Blood', image: '/images/46.png' },
        { id: 47, name: 'Midsommar', image: '/images/47.png' },
        { id: 48, name: 'Dark Waters', image: '/images/48.png' },
        { id: 49, name: 'Dunkirk', image: '/images/49.png' },
        { id: 50, name: '13 Hours)', image: '/images/50.png' },
        { id: 51, name: 'Never Look Away', image: '/images/51.png' },
        { id: 52, name: 'The Impossible', image: '/images/52.png' },
        { id: 53, name: 'Gone Girl', image: '/images/53.png' },
        { id: 54, name: 'Guardians of the Galaxy', image: '/images/54.png' },
        { id: 55, name: 'Whiplash', image: '/images/55.png' },
        { id: 56, name: 'The Wolf of Wall Street', image: '/images/56.png' },
        { id: 57, name: 'Rush', image: '/images/57.png' },
        { id: 58, name: 'Prisoners', image: '/images/58.png' },
        { id: 59, name: 'Inception', image: '/images/59.png' },
        { id: 60, name: 'How to Train Your Dragon', image: '/images/60.png' },
        { id: 61, name: '3 Idiots', image: '/images/61.png' },
        { id: 62, name: 'The Secret in Their Eyes', image: '/images/62.png' },
        { id: 63, name: 'The Dark Knight', image: '/images/63.png' },
        { id: 64, name: 'Million Dollar Baby', image: '/images/64.png' },
        { id: 65, name: 'Downfall', image: '/images/65.png' },
        { id: 66, name: 'Before Sunset', image: '/images/66.png' },
        {
          id: 67,
          name: 'The Lord of the Rings: The Two Towers',
          image: '/images/67.png',
        },
        {
          id: 68,
          name: 'Spider-Man: Into the Spider-Verse',
          image: '/images/68.png',
        },
        {
          id: 69,
          name: 'Star Wars: Episode VI - Return of the Jedi',
          image: '/images/69.png',
        },
        { id: 70, name: 'The Hunt', image: '/images/70.png' },
        { id: 71, name: 'Up', image: '/images/71.png' },
        { id: 72, name: 'Ford v Ferrari', image: '/images/72.png' },
        { id: 73, name: 'A Beautiful Mind', image: '/images/73.png' },
        { id: 74, name: 'Marriage Story', image: '/images/74.png' },
        { id: 75, name: 'Warrior', image: '/images/75.png' },
        { id: 76, name: 'Shutter Island', image: '/images/76.png' },
        { id: 77, name: 'Memories of Murder', image: '/images/77.png' },
        { id: 78, name: 'Mad Max: Fury Road', image: '/images/78.png' },
        { id: 79, name: 'The Help', image: '/images/79.png' },
        { id: 80, name: 'Watchmen', image: '/images/80.png' },
        { id: 81, name: '1917', image: '/images/81.png' },
        { id: 82, name: 'A Christmas Story', image: '/images/82.png' },
        { id: 83, name: 'The Lighthouse', image: '/images/83.png' },
        { id: 84, name: 'Elf', image: '/images/84.png' },
        { id: 85, name: 'Frozen', image: '/images/85.png' },
        { id: 86, name: 'Togo', image: '/images/86.png' },
        { id: 87, name: 'Ad Astra', image: '/images/87.png' },
        { id: 88, name: "Dr. Seuss' The Grinch", image: '/images/88.png' },
        {
          id: 89,
          name: 'Jumanji: Welcome to the Jungle',
          image: '/images/89.png',
        },
        { id: 90, name: 'The Polar Express', image: '/images/90.png' },
      ]);
    });
};
